name: Multi-language Workflow

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      # Étapes pour Deno
      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Run linter for Deno
        run: deno lint

      - name: Run tests for Deno
        run: deno test -A

      # Étapes pour exécuter un script Python (ajoutez ou supprimez selon vos besoins)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: pip install -r requirements.txt  # Si vous avez un fichier requirements.txt

      - name: Run Python tests
        run: python -m pytest  # Ou toute autre commande de test Python

      # Étapes pour exécuter un script JavaScript (ajoutez ou supprimez selon vos besoins)
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install JavaScript dependencies
        run: npm install

      - name: Run JavaScript tests
        run: npm test
