# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Node.js and run your JavaScript tests and linting.
name: JavaScript Testing

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Mettez la version de Node.js que vous souhaitez utiliser ici

      # Installation des dépendances si nécessaire
      - name: Install dependencies
        run: npm install

      # Exécutez ici vos tests, linting, etc.
      - name: Run JavaScript linter (remplacez cette commande par votre outil de linting si différent)
        run: npm run lint

      - name: Run JavaScript tests (remplacez cette commande par votre outil de tests si différent)
        run: npm test
